[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['forge-std/=dependencies/forge-std-1.8.2/src/']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = { version = "1.8.2" }
